version: "3"

services:
  app:
    build: .
    restart: always
    container_name: "valida-pix-teste-server"
    ports:
      - "3333:3333"
    command: npm run start:dev
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: "valida-pix-teste-database"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "valida_pix_teste_password"
      POSTGRES_DB: "valida-pix-db-postgres"
    ports:
      - "5432:5432"
volumes:
  pgdata: